name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run type checks
        run: npx tsc -p tsconfig.json --noEmit
      - name: Build frontend
        run: npm run build
      - name: Test frontend
        run: npm test